name: freefare
description: Provides lightweight yet convenient bindings to Freefare by using dart:ffi
version: 0.0.1
homepage: https://github.com/longtn-imt/freefare.dart/tree/main/freefare
issue_tracker: https://github.com/longtn-imt/freefare.dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

# This package supports all platforms listed below.
platforms:
  android:
  ios:

topics:
  - nfc
  - ffi

dependencies:
  collection: ^1.18.0
  ffi: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.6
  ffigen: ^9.0.1
  lints: ^3.0.0
